import 'package:flutter/material.dart';
import 'package:islami_app/ui/home/Quran/sura_name.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';


class QuranScreen extends StatelessWidget {
  static const String routeName = 'quran-screen';
  List<String> suraName = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  @override
  Widget build(BuildContext context) {

    return Column(
      children: [
        Expanded(
            flex: 1,
            child: Image.asset('assets/images/qur2an_screen_logo.png')),
        Divider(
          color: Theme.of(context).accentColor,
          thickness: 2,
        ),
         Text(
         AppLocalizations.of(context)!.verseName,
          style: Theme.of(context).textTheme.headlineMedium,
        ),
        Divider(
          color: Theme.of(context).accentColor,
          thickness: 2,
        ),
        Expanded(
            flex: 3,
            child: ListView.separated(
                itemBuilder: (context, index) =>
                    SuraNameWidget(suraName[index], index),
                separatorBuilder: (context, index) {
                  return Divider(
                    color: Theme.of(context).accentColor,
                    thickness: 2,
                    indent: 34,
                    endIndent: 34,
                  );
                },
                itemCount: suraName.length))
      ],
    );
  }
}
